"""Added inspiration field to the recipe table

Revision ID: 56b6764ae94a
Revises: None
Create Date: 2016-10-27 22:40:30.168097

"""

# revision identifiers, used by Alembic.
revision = '56b6764ae94a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('inspiration', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'inspiration')
    ### end Alembic commands ###
