"""Added dairy-free, soy-free, and date created fields to Recipe

Revision ID: a34e9acbbe47
Revises: 56b6764ae94a
Create Date: 2017-06-02 00:31:44.234980

"""

# revision identifiers, used by Alembic.
revision = 'a34e9acbbe47'
down_revision = '56b6764ae94a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('dairy_free_recipe', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('soy_free_recipe', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'soy_free_recipe')
    op.drop_column('recipes', 'date_created')
    op.drop_column('recipes', 'dairy_free_recipe')
    ### end Alembic commands ###
